#!/bin/bash
#prepare
current_dir=$(pwd)
script_dir=$(dirname "$0")
if [ "$script_dir" = "." ]
then
script_dir="$current_dir"
fi

#load properties
auto_build_env_path=`sed '/^\#/d' "$script_dir/conf/env-config.properties" | grep 'autobuild.env.path'  | tail -n 1 | cut -d "=" -f2- | sed 's/^[[:space:]]*//;s/[[:space:]]*$//'`
system_java_home_path=`sed '/^\#/d' "$script_dir/conf/env-config.properties" | grep 'system.java.home'  | tail -n 1 | cut -d "=" -f2- | sed 's/^[[:space:]]*//;s/[[:space:]]*$//'`
build_interval=`sed '/^\#/d' "$script_dir/conf/env-config.properties" | grep 'build.interval'  | tail -n 1 | cut -d "=" -f2- | sed 's/^[[:space:]]*//;s/[[:space:]]*$//'`

export JAVA_HOME=${system_java_home_path}
export PATH=${PATH}:${JAVA_HOME}/bin

java -jar "$auto_build_env_path/resources/autob-daemon.jar" "$auto_build_env_path/resources/launch-autob" ${build_interval}