/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * WelcomeScreen.java
 *
 * Created on 09-mar-2012, 22:22:40
 */
package nbautobuild.wizard.pages;

import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import nbautobuild.core.ResourcesManager;

/**
 *
 * @author Martin
 */
public class FinishScreen extends javax.swing.JPanel {
    
    public static int TIME_TASK_UPDATE_ENVIRONMENT = 20;
    public static int TIME_TASK_GENERATE_PROPERTIES = 60;
    public static int TIME_TASK_CREATE_SHORTCUT = 20;
    
    private static boolean execAutobNow = false;

    /** Creates new form WelcomeScreen */
    public FinishScreen() {
        initComponents();
        initialize();
    }
    
    private void initialize() {
        chkExecAutob.addItemListener(new ItemListener() {

            @Override
            public void itemStateChanged(ItemEvent e) {
                execAutobNow = !execAutobNow;
            }
        });
    }
    
    public static void applyConfiguration() {
        try {
            ResourcesManager rm = ResourcesManager.instance();
            rm.expandResources();
            if(execAutobNow) rm.executeAutobuild();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Oops", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Oops", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public static void setCurrentTask(String taskName) {
        lblCurrentTask.setText(taskName);
    }

    public static void addProgress(int ammount) {
        throw new UnsupportedOperationException("Not supported yet.");
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chkExecAutob = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        lblCurrentTask = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(550, 430));
        setMinimumSize(new java.awt.Dimension(550, 430));
        setPreferredSize(new java.awt.Dimension(550, 430));

        chkExecAutob.setText("Execute autobuild now");

        jLabel1.setText("All your configurations will be applied when you press the 'Finish' button.");

        lblCurrentTask.setText("Stopped");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCurrentTask)
                    .addComponent(jLabel1)
                    .addComponent(chkExecAutob))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(chkExecAutob)
                .addGap(88, 88, 88)
                .addComponent(lblCurrentTask)
                .addContainerGap(229, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkExecAutob;
    private javax.swing.JLabel jLabel1;
    private static javax.swing.JLabel lblCurrentTask;
    // End of variables declaration//GEN-END:variables
    
}
